/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xE0, 0x47, 0x46, 0x52, 0x09, 0xAD, 0xB4, 0x94}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define POINTING_DEVICE_ROTATION_180
#define POINTING_DEVICE_INVERT_X
//#define POINTING_DEVICE_INVERT_Y

#define MASTER_RIGHT

#define ENCODER_A_PINS { GP29}
#define ENCODER_B_PINS { GP28}
#define ENCODER_RESOLUTIONS { }
//#define ENCODER_A_PINS_RIGHT { GP29 }
//#define ENCODER_B_PINS_RIGHT { GP28 }
#define ENCODER_RESOLUTIONS_RIGHT { 4 }


#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_CS_PIN GP2
#define POINTING_DEVICE_SCLK_PIN GP1
#define POINTING_DEVICE_SDIO_PIN GP0
// Not supported for split keyboard
// #define POINTING_DEVICE_MOTION_PIN GP8

#define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW

#define SPLIT_POINTING_ENABLE

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE

#define HOLD_ON_OTHER_KEY_PRESS
